DROP function IF EXISTS `UUID_TO_BIN`;

DELIMITER $$
CREATE FUNCTION `UUID_TO_BIN`
(
	vUuid VARCHAR(36)
) 
RETURNS binary(16)
READS SQL DATA DETERMINISTIC
BEGIN

  SET @u = UNHEX(REPLACE(vUuid, '-', ''));
  RETURN CONCAT(
    SUBSTR(@u, 7, 2), SUBSTR(@u, 5, 2),
    SUBSTR(@u, 1, 4), SUBSTR(@u, 9, 8)
  );
END$$

DELIMITER ;