DROP TABLE IF EXISTS mstcompany;

CREATE TABLE `mstcompany` (
    CompanyGuid		BINARY  (16) NOT NULL,
   `CompanyName` varchar(150) CHARACTER SET utf8 NOT NULL,
   `ATSClientID` int(11) DEFAULT NULL,
   `Description` text CHARACTER SET utf8,
   `DomainName` int(11) DEFAULT NULL,
   `Address` text CHARACTER SET utf8,
   `Location` int(11) DEFAULT NULL,
   `State` int(11) DEFAULT NULL,
   `Zipcode` int(11) DEFAULT NULL,
   `PrimaryPersonName` varchar(2000) CHARACTER SET utf8 DEFAULT NULL,
   `AssignedRecruiter` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
   `Phone` varchar(2000) DEFAULT NULL,
   `WorkPhone` varchar(2000) DEFAULT NULL,
   `Fax` varchar(2000) DEFAULT NULL,
   `Email` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
   `URL` text CHARACTER SET utf8,
   `CompanyLogo` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
	OrgGuid				BINARY  (16) DEFAULT NULL,   
   `IsActive` bit(1) DEFAULT b'1',
	CreatedByGuid		BINARY  (16) DEFAULT NULL,
    CreatedDate			datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ModifiedByGuid		BINARY  (16) DEFAULT NULL,
    ModifiedDate			datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   
   `TemplateTxt` longtext CHARACTER SET utf8,
   `AssignedRecruiters` varchar(250) CHARACTER SET utf8 DEFAULT NULL,
   `SourceCount` int(11) DEFAULT '200',
   `CareerBuilderSourceCount` int(11) DEFAULT '0',
   `CareerBuilderV2SourceCount` int(11) DEFAULT NULL,
   `NexxtSourceCount` int(11) DEFAULT '0',
   `ResumeLibrarySourceCount` int(11) DEFAULT '0',
   `EFinancialSourceCount` int(11) DEFAULT '0',
   `MonsterSourceCount` int(11) DEFAULT '0',
   `DiceSourceCount` int(11) DEFAULT '0',
   `IndeedSourceCount` int(11) DEFAULT '0',
   `InternalSourceCount` int(11) DEFAULT '0',
   `SubsidiaryCompanies` text CHARACTER SET utf8,
   `CVLibrarySourceCount` int(11) DEFAULT NULL,
   `CWJobsSourceCount` int(11) DEFAULT NULL,
   `TotalJobsSourceCount` int(11) DEFAULT NULL,
   `JobSiteSourceCount` int(11) DEFAULT NULL,
   `AryaVaultSourceCount` int(11) DEFAULT NULL,
   `NaukriSourceCount` int(11) DEFAULT NULL,
   `30SourceLimit` int(11) DEFAULT NULL,
   PRIMARY KEY (`CompanyGuid`),
   UNIQUE KEY `ATSClientID_UNIQUE` (`ATSClientID`,`OrgGuid`),
   KEY `mstSearchIndex` (`CompanyGuid`) USING BTREE,
   KEY `OrgGuid` (`OrgGuid`),
   KEY `ClientID` (`ATSClientID`),
   FULLTEXT KEY `SrchCompanyName` (`CompanyName`),
   FULLTEXT KEY `address` (`Address`)
 ) ENGINE=InnoDB AUTO_INCREMENT=110235 DEFAULT CHARSET=latin1