DROP TABLE IF EXISTS mstorganization;
CREATE TABLE mstorganization (
	OrgGuid					BINARY  (16) NOT NULL,
	OrganizationName		varchar(2000) DEFAULT NULL,
	LocationId				int(11) DEFAULT NULL,
	OfficePhone				varchar(2000) DEFAULT NULL,
	MobileNo				varchar(2000) DEFAULT NULL,
	ContactPerson			varchar(2000) DEFAULT NULL,
	CPDesignation			varchar(2000) DEFAULT NULL,
	CPPhone					varchar(2000) DEFAULT NULL,
	CPMobile				varchar(2000) DEFAULT NULL,
	NatureOfClient			int(11) DEFAULT '0',
	Turnover				varchar(2000) DEFAULT NULL,
	CMMLevel				int(11) DEFAULT NULL,
	Domain					varchar(45) DEFAULT NULL,
	OrganizationType		int(11) DEFAULT '0',
	OrgDesc					varchar(2000) DEFAULT NULL,
	OrgPageLogo				text,
	OrgPageHeader			text,
	OrgPageTagLine			text,
	OrgPageFooter			text,
	CPEmail					varchar(2000) DEFAULT NULL,
	EmailFooter				text,
	OrgHomePageLink			varchar(1000) DEFAULT NULL,
	Facebooklink			varchar(2000) DEFAULT NULL,
	FacebookJobPage			varchar(2000) DEFAULT NULL,
	Twitterlink				varchar(2000) DEFAULT NULL,
	Linkedinlink			varchar(2000) DEFAULT NULL,
	OrgJobsPageLink			varchar(1000) DEFAULT NULL,
	OrgJobViewURL			varchar(2000) DEFAULT NULL,
	MajorTechnologies		varchar(2000) DEFAULT NULL,
	Divisions				int(11) DEFAULT NULL,
	IsActive				bit(1) DEFAULT b'1',	
	
	Address					text,
	OrgType					varchar(100) DEFAULT NULL,
	OrgType1				varchar(100) DEFAULT NULL,
	LoginUserName			varchar(100) DEFAULT NULL,
	LoginPassword			varchar(100) DEFAULT NULL,
	OrgCode					varchar(2000) DEFAULT NULL,
	IsArya					bit(1) DEFAULT b'1',
	IsSocialArya			bit(1) DEFAULT b'0',
	IsCorporate				bit(1) DEFAULT b'0',
	SubscriptionEndDate		datetime DEFAULT NULL,
	EntityId				varchar(200) DEFAULT NULL,
	AgencyDomain			varchar(200) DEFAULT NULL,
	AuthenticatedCountries	varchar(2000) DEFAULT '1',
	ContactProviderServiceEnabled bit(1) DEFAULT b'0',
	MoversEnabled			bit(1) DEFAULT b'0',
	CandidateScoreEnabled	bit(1) DEFAULT b'0',
	OrgSourceCount			int(11) DEFAULT NULL,
	JobCountLimit			int(11) DEFAULT NULL,
	AdditionalATSInfo		text,
	IsJobBoardEnabled		int(11) DEFAULT '0',
	IsPersonalityProviderEnabled bit(1) DEFAULT b'0',
	SessionTimeoutDuration int(11) DEFAULT '10',
	IdentityProviderIdentifier varchar(255) DEFAULT NULL,

	-- Audit details
	CreatedByGuId			BINARY  (16) DEFAULT NULL,
	CreatedDate				datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ModifiedByGuId			BINARY  (16) DEFAULT NULL,
	ModifiedDate			datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   

	PRIMARY KEY (OrgGuId)
) ENGINE=InnoDB AUTO_INCREMENT=2550 DEFAULT CHARSET=latin1