DROP TABLE IF EXISTS orgconfigsettings;

CREATE TABLE `orgconfigsettings` (
   `idOrgconfgSettingId` int(11) NOT NULL AUTO_INCREMENT,
   `AddLogoToResume` bit(1) DEFAULT NULL,
   `OrgGuid` int(11) DEFAULT NULL,
   `CreatedbyGuid` int(11) DEFAULT NULL,
   `CreatedDate` datetime DEFAULT NULL,
   `ModifiedbyGuid` int(11) DEFAULT NULL,
   `ModifiedDate` datetime DEFAULT NULL,
   `CandStatusEmailToRecruiter` int(11) DEFAULT '0',
   `JobCodePrefix` varchar(500) DEFAULT NULL,
   `IsRemoveClientInJobDesc` int(11) DEFAULT '0',
   `IsMailBoxReadingNotification` bit(1) DEFAULT b'1',
   `IsJobNotesMailNotification` int(11) DEFAULT '0',
   `IsDuplicateJobCodeAllow` int(11) DEFAULT '0',
   `IsSSNNoValidation` int(11) DEFAULT '0',
   `IsCandStatusEmailToCCAddress` int(11) DEFAULT '0',
   `CandStatusEmailToSubmittedRecruiter` int(11) DEFAULT '0',
   `CandStatusEmailToCCAddress` varchar(2000) DEFAULT NULL,
   `IsJobStatusMailNotification` int(11) DEFAULT '0',
   `IsAutoJobClosedStatus` int(11) DEFAULT '0',
   `CandidateOwnerByStatus` varchar(500) DEFAULT NULL,
   `DisabledEmailNotificationCandidateStatus` varchar(650) DEFAULT NULL,
   `checkaryacandstatus` varchar(100) DEFAULT NULL,
   `checkaryacandstatusdays` int(11) DEFAULT '0',
   `IsAddtionalJobFieldsMandatory` int(11) DEFAULT '0',
   `IsRecruiterJobAssignToAllow` int(11) DEFAULT '0',
   `IsCandidateStatusValidation` int(11) DEFAULT '0',
   `EmailCampaignCountStatus` int(11) DEFAULT '1',
   `AryaEmailCount` int(11) DEFAULT '1',
   `IsIndividualUser` int(11) DEFAULT '0',
   `IsAryaDripMailsEnabled` int(11) DEFAULT '0',
   `AryaDripMailStartDate` varchar(450) DEFAULT NULL,
   `AryaDripEmailCountPerDay` int(11) DEFAULT '1',
   `AryaDripEmailCountOfCandidatePerJob` int(11) DEFAULT '3',
   `IsAutoSourceProfilesEnabled` int(11) DEFAULT '0',
   `IsAryaMailsEnabled` int(11) DEFAULT '1',
   `AutoSourceProfilesEnabledDate` varchar(45) DEFAULT NULL,
   `ShortListonPost` tinyint(4) DEFAULT '0',
   `ShowPIPL` tinyint(4) DEFAULT '0',
   `ISNOTES` tinyint(4) DEFAULT '0',
   `ISJobPublish` tinyint(4) DEFAULT '0',
   `Isselecttemplate` tinyint(4) DEFAULT '0',
   `IsShortlistonpush` tinyint(1) DEFAULT '0',
   `IsPushonShortlist` tinyint(1) DEFAULT '0',
   `OrgLevelMiles` varchar(45) DEFAULT '50',
   `JobBoardAllow` int(11) NOT NULL,
   `ContractServiceQuota` int(11) DEFAULT NULL,
   `ContractServiceProviders` varchar(50) DEFAULT NULL,
   `SMSProviders` varchar(50) DEFAULT 'CLICKSEND',
   `ContactSettings` varchar(50) DEFAULT NULL,
   `JobIntelEnable` int(11) DEFAULT '0',
   `IsSocialDeactivateEmailEnable` int(11) DEFAULT '1',
   `IsSocialDeactivateTextEmailEnable` int(11) DEFAULT '1',
   `IsSocialDeactivateHtmlEmailEnable` int(11) DEFAULT '0',
   `IsSocialAryaDripMailsEnabled` int(11) DEFAULT '0',
   `SocialAryaDripMailStartDate` varchar(450) DEFAULT NULL,
   `SocialAryaDripEmailCountPerDay` int(11) DEFAULT '1',
   `SocialAryaDripEmailCountOfCandidatePerJob` int(11) DEFAULT '3',
   `IsSocialDirectEnable` tinyint(1) DEFAULT '0',
   `CareerBuilderSourceCount` int(11) DEFAULT NULL,
   `CareerBuilderV2SourceCount` int(11) DEFAULT NULL,
   `NexxtSourceCount` int(11) DEFAULT '0',
   `ResumeLibrarySourceCount` int(11) DEFAULT '0',
   `EFinancialSourceCount` int(11) DEFAULT '0',
   `MonsterSourceCount` int(11) DEFAULT NULL,
   `DiceSourceCount` int(11) DEFAULT NULL,
   `IndeedSourceCount` int(11) DEFAULT NULL,
   `InternalSourceCount` int(11) DEFAULT NULL,
   `CVLibrarySourceCount` int(11) DEFAULT NULL,
   `CWJobsSourceCount` int(11) DEFAULT NULL,
   `TotalJobsSourceCount` int(11) DEFAULT NULL,
   `JobSiteSourceCount` int(11) DEFAULT NULL,
   `AryaVaultSourceCount` int(11) DEFAULT NULL,
   `NaukriSourceCount` int(11) DEFAULT NULL,
   `IsSingleSession` int(11) DEFAULT '1',
   `IsNewDiceAPIAutoDownload` int(11) DEFAULT '0',
   `IsSimilarJobSourcingEnabled` int(11) DEFAULT '0',
   `IsSimilarJobAutoSourcingEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingCBEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingNexxtEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingEFinancialEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingDiceEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingMonsterEnabled` int(11) DEFAULT '0',
   `IsSimilarJobSourcingIndeedEnabled` int(11) DEFAULT '0',
   `IsUserCreation` tinyint(1) DEFAULT '0',
   `IsElasticForSocialEnable` int(11) DEFAULT '0',
   `IsChatBotEnable` int(11) DEFAULT '0',
   `SocialAdminTextTemplateId` int(11) DEFAULT '0',
   `NonSocialAdminTextTemplateId` int(11) DEFAULT '0',
   `IsUsercreationemailToUser` tinyint(1) DEFAULT '0',
   `ChatBotSecretKey` varchar(450) DEFAULT NULL,
   `AutoPullContact` bit(1) DEFAULT b'0',
   `AutoPullContactCount` int(11) DEFAULT NULL,
   `IsAutoSendEmailEnabled` bit(1) DEFAULT b'0',
   `IsAutoSendSmsEnabled` bit(1) DEFAULT b'0',
   `IsSocialMasterProfileEnable` tinyint(4) DEFAULT '0',
   `Iscanpush` tinyint(1) DEFAULT '0',
   `IsSocialCanPush` tinyint(1) DEFAULT '0',
   `IsIndeedCanPush` tinyint(1) DEFAULT '0',
   `IsJobUpdateAllow` tinyint(1) DEFAULT '0',
   `IsHighlightKeywordsinResme` tinyint(1) DEFAULT '0',
   `IsReplenishment` int(11) DEFAULT '0',
   `IsDirectSimilarJobCallEnabled` int(11) DEFAULT '0',
   `CandidateLimit` int(11) DEFAULT NULL,
   `DiversityPercentage` float DEFAULT NULL,
   `ChatBotOrgId` int(11) DEFAULT NULL,
   `PersistedIntelEnabled` tinyint(1) DEFAULT '0',
   `IsGoldsetCriteriaOnly` bit(1) NOT NULL DEFAULT b'0',
   `issocialiconsenable` int(11) DEFAULT '1',
   `IsInternalElastic` bit(1) DEFAULT b'0',
   `IsSimilarJobSourcingResumeLibraryEnabled` int(11) DEFAULT '0',
   `IsSaveToProcessTable` bit(1) DEFAULT b'0',
   `Is30Enabled` bit(1) NOT NULL DEFAULT b'0',
   `30SourceLimit` smallint(6) NOT NULL DEFAULT '100',
   `MaxAllowed30SourceLimit` int(11) DEFAULT NULL,
   `30StackRankType` enum('Mix','Rank') NOT NULL DEFAULT 'Mix',
   `IsResumeParsingEnabledRLTI` tinyint(4) NOT NULL DEFAULT '0',
   `ScoreNormalizationMinValue` decimal(9,6) NOT NULL DEFAULT '0.000000',
   `ScoreNormalizationMaxValue` decimal(9,6) NOT NULL DEFAULT '3.000000',
   `ScoreNormalizationDecimalPlaces` tinyint(4) NOT NULL DEFAULT '2',
   `ShowCandidateScore` bit(1) DEFAULT b'0',
   `AllowClassicWith30` bit(1) DEFAULT b'0',
   `MaxDownloadLimit` int(11) DEFAULT '0',
   `ATSOrgId` int(11) DEFAULT NULL,
   `IsAutoSourcingEnabled` bit(1) NOT NULL DEFAULT b'1',
   `ChatSummaryViewUrl` text,
   `WhitelabelId` varchar(20) DEFAULT NULL,
   PRIMARY KEY (`idOrgconfgSettingId`),
   UNIQUE KEY `IDX_ORGGuid` (`OrgGuid`),
   KEY `IsChatBotEnable` (`IsChatBotEnable`),
   KEY `IsElasticForSocialEnable` (`IsElasticForSocialEnable`),
   KEY `ATSorgid` (`ATSOrgId`)
 ) ENGINE=InnoDB AUTO_INCREMENT=1790 DEFAULT CHARSET=latin1